services:
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    volumes:
      - "postgres_data:/var/lib/postgres/data"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "psql -U postgres -d postgres -c 'SELECT 1;'",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: